[versions]
agp = "8.5.2"
activity = "1.4.0"
kotlin = "2.0.20"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycle = "2.4.1"
lifecycleRuntimeKtx = "2.8.4"
activityCompose = "1.9.1"
composeBom = "2024.06.00"
composeCompiler = "1.5.14"
hilt = "2.51.1"
androidxHilt = "1.2.0"
navigationCompose = "2.7.7"
retrofit = "2.11.0"
retrofit-bom = "2.11.0"
gson = "2.10.1"
okhttp = "4.12.0"
okhttp-logging-interceptor = "4.10.0"
okhttp-urlconnection = "4.9.1"
appcompat = "1.7.0"
material = "1.12.0"
coroutines = "1.7.3"
coreKtxVersion = "1.6.1"
roomKtx = "2.6.1"
datastore = "1.1.1"
gradleplugin = "8.6.0"
threeten = "1.3.1"
timber = "5.0.1"
compileSdk = "34"
minSdk = "30"
targetSdk = "34"
desugarLibs = "1.1.5"
datetime = "0.2.1"
kotlinx-serialization-json = "1.7.2"
kspplugin = "2.0.20-1.0.25"
desugarJdk = "2.1.2"
compose-destination = "1.11.6"
lottie = "6.5.2"
androidx-paging = "3.3.2"
coil = "2.7.0"
kotlin-serialization-converter = "0.8.0"
kakao-auth = "2.20.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
desugarLibs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHilt" }
hilt-testing-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

# navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# 서버 통신
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofit" }
retrofit-kotlin-serialization-converter = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
retrofit-response-type-keeper = { module = "com.squareup.retrofit2:response-type-keeper", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging-interceptor" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttp-urlconnection" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# 코루틴
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }

# DataStore
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

# ThreeTen
threeten = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threeten" }

agp = { module = "com.android.tools.build:gradle", version.ref = "gradleplugin" }
kotlin-gradleplugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-extension = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-three = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-junit = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-destination-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destination" }
compose-destination-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destination" }
compose-lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
compose-paging = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }

# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

# KaKao
kakao-auth = { module = "com.kakao.sdk:v2-user", version.ref = "kakao-auth" }

[bundles]
compose = [
    "compose-ui",
    "compose-foundation",
    "compose-ui-tooling",
    "androidx-activity-compose",
    "compose-animation",
    "compose-viewmodel",
    "compose-material",
    "compose-material-three",
    "compose-material-icons-extended",
    "compose-material-icons",
    "compose-runtime",
    "compose-ui-tooling-preview",
    "hilt-navigation",
    "compose-lottie",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspplugin" }